default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: check-ast
      - id: detect-private-key
      - id: pretty-format-json
        args: [ --autofix ]
      - id: check-yaml
        exclude: ^k8s/templates/
      - id: check-toml
      - id: check-json
      - id: check-docstring-first
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ "--profile=black" ]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [ "--line-length=120" ]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [ "--max-line-length=120" ]

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: ["--ignore", "B6", "--msg-filename"]
