"""initial tables

Revision ID: e86d86529845
Revises:
Create Date: 2025-08-29 07:37:59.442081

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e86d86529845"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sap_credit_limits",
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("segment", sa.String(length=50), nullable=False),
        sa.Column("sap_data", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_sap_credit_customer_segment",
        "sap_credit_limits",
        ["customer_code", "segment"],
        unique=True,
    )
    op.create_index("idx_sap_credit_updated", "sap_credit_limits", ["updated_at"], unique=False)
    op.create_index(
        op.f("ix_sap_credit_limits_customer_code"),
        "sap_credit_limits",
        ["customer_code"],
        unique=False,
    )
    op.create_table(
        "sap_customers",
        sa.Column("customer_code", sa.String(length=50), nullable=False),
        sa.Column("sap_data", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sap_customer_code", "sap_customers", ["customer_code"], unique=False)
    op.create_index("idx_sap_customer_created", "sap_customers", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_sap_customers_customer_code"),
        "sap_customers",
        ["customer_code"],
        unique=True,
    )
    op.create_table(
        "sap_sales_orders",
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("customer_code", sa.String(length=50), nullable=True),
        sa.Column("document_date", sa.DateTime(), nullable=True),
        sa.Column("sap_data", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sap_order_customer", "sap_sales_orders", ["customer_code"], unique=False)
    op.create_index("idx_sap_order_date", "sap_sales_orders", ["document_date"], unique=False)
    op.create_index("idx_sap_order_number", "sap_sales_orders", ["order_number"], unique=False)
    op.create_index(
        op.f("ix_sap_sales_orders_customer_code"),
        "sap_sales_orders",
        ["customer_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sap_sales_orders_order_number"),
        "sap_sales_orders",
        ["order_number"],
        unique=True,
    )
    op.create_table(
        "sync_logs",
        sa.Column("sync_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=True),
        sa.Column("records_created", sa.Integer(), nullable=True),
        sa.Column("records_updated", sa.Integer(), nullable=True),
        sa.Column("records_failed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sync_log_dates", "sync_logs", ["started_at", "completed_at"], unique=False)
    op.create_index("idx_sync_log_type_status", "sync_logs", ["sync_type", "status"], unique=False)
    op.create_index(op.f("ix_sync_logs_sync_type"), "sync_logs", ["sync_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_logs_sync_type"), table_name="sync_logs")
    op.drop_index("idx_sync_log_type_status", table_name="sync_logs")
    op.drop_index("idx_sync_log_dates", table_name="sync_logs")
    op.drop_table("sync_logs")
    op.drop_index(op.f("ix_sap_sales_orders_order_number"), table_name="sap_sales_orders")
    op.drop_index(op.f("ix_sap_sales_orders_customer_code"), table_name="sap_sales_orders")
    op.drop_index("idx_sap_order_number", table_name="sap_sales_orders")
    op.drop_index("idx_sap_order_date", table_name="sap_sales_orders")
    op.drop_index("idx_sap_order_customer", table_name="sap_sales_orders")
    op.drop_table("sap_sales_orders")
    op.drop_index(op.f("ix_sap_customers_customer_code"), table_name="sap_customers")
    op.drop_index("idx_sap_customer_created", table_name="sap_customers")
    op.drop_index("idx_sap_customer_code", table_name="sap_customers")
    op.drop_table("sap_customers")
    op.drop_index(op.f("ix_sap_credit_limits_customer_code"), table_name="sap_credit_limits")
    op.drop_index("idx_sap_credit_updated", table_name="sap_credit_limits")
    op.drop_index("idx_sap_credit_customer_segment", table_name="sap_credit_limits")
    op.drop_table("sap_credit_limits")
    # ### end Alembic commands ###
